const teamData = [
    {
        country: 'New Zealand',
        nickname: 'Football Ferns',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/New_Zealand.jpg',
        confederation: 'OFC (Host Nation)',
        coach: 'Jitka Klimkova',
        captain: 'Ali Riley',
        group: 'A',
    },
    {
        country: 'Norway',
        nickname: 'The Grasshoppers',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Norway.jpg',
        confederation:'UEFA',
        coach: 'Hege Riise',
        captain: 'Maren Mjelde',
        group: 'A',
    },
    {
        country: 'Philippines',
        nickname: 'Filipinas',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Philippines.jpg',
        confederation: 'AFC',
        coach: 'Alen Stajcic',
        captain: 'Tahnai Annis',
        group: 'A',
    },
    {
        country: 'Switzerland',
        nickname: 'La Nati',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Switzerland.jpg',
        confederation: 'UEFA',
        coach: 'Inka Grings',
        captain: 'Lia Walti',
        group: 'A',
    },
    {
        country: 'Australia',
        nickname: 'Matildas',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Australia.jpg',
        confederation: 'AFC (Host Nation)',
        coach: 'Tony Gustavsson',
        captain: 'Sam Kerr',
        group: 'B',
    },
    {
        country: 'Ireland',
        nickname: 'The Girls In Green',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Ireland.jpg',
        confederation: 'UEFA',
        coach: 'Vera Pauw',
        captain: 'Katie McCabe',
        group: 'B',
    },
    {
        country: 'Nigeria',
        nickname: 'Super Falcons',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Nigeria.jpg',
        confederation: 'CAF',
        coach: 'Randy Waldrum',
        captain: 'Onome Ebi',
        group: 'B',
    },
    {
        country: 'Canada',
        nickname: 'https://www.sciencekids.co.nz/images/pictures/flags96/Canada.jpg',
        image: '',
        confederation: 'CONCACAF',
        coach: 'Beverly Priestman',
        captain: 'Christine Sinclair',
        group: 'B',
    },
    {
        country: 'Spain',
        nickname: 'La Roja',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Spain.jpg',
        confederation: 'UEFA',
        coach: 'Jorge Vilda',
        captain: 'Alexia Putellas',
        group: 'C',
    },
    {
        country: 'Costa Rica',
        nickname: 'La Sele/La Tricolor',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/CostaRica.jpg',
        confederation: 'CONCACAF',
        coach: 'Amelia Valverde',
        captain: 'Shirley Cruz',
        group: 'C',
    },
    {
        country: 'Zambia',
        nickname: 'Copper Queens',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Zambia.jpg',
        confederation: 'CAF',
        coach: 'Bruce Mwape',
        captain: 'Barbra Banda',
        group: 'C',
    },
    {
        country: 'Japan',
        nickname: 'Nadeshiko Japan',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Japan.jpg',
        confederation: 'AFC',
        coach: 'Futoshi Ikeda',
        captain: 'Maya Yoshida',
        group: 'C',
    },
    {
        country: 'England',
        nickname: 'The Lionesses',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/England.jpg',
        confederation: 'UEFA',
        coach: '',
        captain: '',
        group: 'D',
    },
    {
        country: 'Denmark',
        nickname: 'The Red and White',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Denmark.jpg',
        confederation: 'UEFA',
        coach: 'Lars Sondergaard',
        captain: 'Pernille Harder',
        group: 'D',
    },
    {
        country: 'China',
        nickname: 'Steel Roses',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/China.jpg',
        confederation: 'AFC',
        coach: 'Shui Qungxia',
        captain: 'Wu Haiyan',
        group: 'D',
    },
    {
        country: 'TBD: Chile || Haiti || Senegal',
        nickname: '',
        image: '',
        confederation: '',
        coach: '',
        captain: '',
        group: 'D',
    },
    {
        country: 'United States',
        nickname: 'The Gals',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/UnitedStates.jpg',
        confederation: 'CONCACAF',
        coach: 'Vlatko Andonovski',
        captain: 'Becky Sauerbrunn',
        group: 'E',
    },
    {
        country: 'Vietnam',
        nickname: 'Nhung Nu Chien Binh Sao Vang',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Vietam.jpg',
        confederation: 'AFC',
        coach: 'Mai Duc Chung',
        captain: 'Huynh Nhu',
        group: 'E',
    },
    
    {
        country: 'Netherlands',
        nickname: 'Orange Lionesses',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Netherlands.jpg',
        confederation: 'UEFA',
        coach: 'Andries Jonker',
        captain: 'Sherida Spitse',
        group: 'E',
    },
    
    {
        country: 'TBD: Camaroon || Portugal || Thailand',
        nickname: '',
        image: '',
        confederation: '',
        coach: '',
        captain: '',
        group: 'E',
    },
    {
        country: 'France',
        nickname: 'Les Bleues',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/France.jpg',
        confederation: 'UEFA',
        coach: 'Corinne Diacre',
        captain: 'Wendie Renard',
        group: 'F',
    },
    {
        country: 'Jamaica',
        nickname: 'Reggae Girlz',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Jamaica.jpg',
        confederation: 'CONCACAF',
        coach: 'Lorne Donaldson',
        captain: 'Khadija Shaw',
        group: 'F',
    },    {
        country: 'Brazil',
        nickname: 'Canarinhas',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Brazil.jpg',
        confederation: 'CONMEBOL',
        coach: 'Pia Sundhage',
        captain: 'Marta',
        group: 'F',
    },    {
        country: 'TBD: Taipei || Panama || Papua New Guinea || Paraguay',
        nickname: '',
        image: '',
        confederation: '',
        coach: '',
        captain: '',
        group: 'F',
    },
    {
        country: 'Sweden',
        nickname: 'The Blue and Yellow',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Sweden.jpg',
        confederation: 'UEFA',
        coach: 'Peter Gerhardsson',
        captain: 'Caroline Seger',
        group: 'G',
    },
    {
        country: 'South Africa',
        nickname: 'Banyana Banyana',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/SouthAfrica.jpg',
        confederation: 'CAF',
        coach: 'Desiree Ellis',
        captain: 'Janine van Wyk',
        group: 'G',
    },
    {
        country: 'Italy',
        nickname: 'The Blues',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Italy.jpg',
        confederation: 'UEFA',
        coach: 'Milena Bertolini',
        captain: 'Sara Gama',
        group: 'G',
    },
    {
        country: 'Argentina',
        nickname: 'La Albiceleste',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Argentina.jpg',
        confederation: 'CONMEBOL',
        coach: 'German Portanova',
        captain: 'Vanina Correa',
        group: 'G',
    },
    {
        country: 'Germany',
        nickname: 'Die Nationalelf',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Germany.jpg',
        confederation: 'UEFA',
        coach: 'Martina Voss-Tecklenburg',
        captain: 'Alexandra Popp',
        group: 'H',
    },
    {
        country: 'Morocco',
        nickname: 'Atlas Lionesses',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Morocco.jpg',
        confederation: 'CAF',
        coach: 'Reynald Pedros',
        captain: 'Ghizlane Chebbak',
        group: 'H',
    },
    {
        country: 'Colombia',
        nickname: 'Las Chicas Superpoderosas',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/Colombia.jpg',
        confederation: 'CONMEBOL',
        coach: 'Nelson Abadia',
        captain: 'Daniela Montoya',
        group: 'H',
    },
    {
        country: 'South Korea',
        nickname: 'Taegeuk Nangja',
        image: 'https://www.sciencekids.co.nz/images/pictures/flags96/SouthKorea.jpg',
        confederation: 'AFC',
        coach: 'Collin Bell',
        captain: 'Kim Hye-ri',
        group: 'H',
    },

]

module.exports = teamData;